FROM dunglas/frankenphp:php8.2-alpine

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Install Git
RUN apk add --no-cache git nodejs npm

# Install PHP extensions
RUN docker-php-ext-install -j$(nproc) pdo_mysql

# Increase max file size in php.ini
RUN echo "upload_max_filesize = 20M" >> /usr/local/etc/php/conf.d/max-fileupload.ini && \
    echo "post_max_size = 20M" >> /usr/local/etc/php/conf.d/max-fileupload.ini

# Set the working directory
WORKDIR /app

# Copy the application code
COPY . /app

# Install the dependencies
RUN composer install && npm install

# Build the assets
RUN npm run build

# link the storage directory
RUN php artisan storage:link
