FROM dunglas/frankenphp:php8.2-alpine

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Install Git
RUN apk add --no-cache git nodejs npm

# Install PHP extensions
RUN docker-php-ext-install -j$(nproc) pdo_mysql

# Increase max file size in php.ini
RUN echo "upload_max_filesize = 20M" >> /usr/local/etc/php/conf.d/max-fileupload.ini && \
    echo "post_max_size = 20M" >> /usr/local/etc/php/conf.d/max-fileupload.ini

# Set the working directory
WORKDIR /app

# Copy the application code
COPY package.json package-lock.json ./
COPY composer.json composer.lock ./

# Install the dependencies
RUN composer install --optimize-autoloader --no-scripts && npm install

# Copy the rest of the application code
COPY . .

# change the permissions
RUN chown -R www-data:www-data /app && \
    find /app -type d -exec chmod 755 {} \; && \
    find /app -type f -exec chmod 644 {} \;

# disconver packages
RUN php artisan package:discover --ansi

# Build the assets
RUN npm run build

# link the storage directory
RUN php artisan storage:link
