# Required metadata
sonar.projectKey=HepiKorea

# Language: check for specific language files
sonar.language=php,vue

# Patterns for PHP files
sonar.lang.patterns.php=**/*[!.blade].php

# Patterns for Vue files
sonar.lang.patterns.vue=resources/js/Pages/**/*.vue

# Only scan the app folder for PHP files
sonar.inclusions=app/**,routes/*,resources/js/Pages/**