import { route as routeFn } from 'ziggy-js';

declare global {
    var route: typeof routeFn;
}

declare module 'vue' {
    interface ComponentCustomProperties {
        route: typeof routeFn;
    }
}


/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "debugbar.openhandler": [],
    "debugbar.clockwork": [
        {
            "name": "id",
            "required": true
        }
    ],
    "debugbar.assets.css": [],
    "debugbar.assets.js": [],
    "debugbar.cache.delete": [
        {
            "name": "key",
            "required": true
        },
        {
            "name": "tags",
            "required": false
        }
    ],
    "debugbar.queries.explain": [],
    "sanctum.csrf-cookie": [],
    "ignition.healthCheck": [],
    "ignition.executeSolution": [],
    "ignition.updateConfig": [],
    "api.ping": [],
    "api.": [
        {
            "name": "id",
            "required": true
        }
    ],
    "home": [],
    "auth.login": [],
    "auth.register": [],
    "auth.": [],
    "auth.index": [],
    "auth.logout": [],
    "auth.google": [],
    "auth.callback": [],
    "auth.verify": [],
    "auth.verify_code": [],
    "auth.forgot_password": [],
    "auth.reset_password": [],
    "auth.set_password": [],
    "auth.profile": [],
    "auth.notification": [],
    "auth.address": [],
    "product.index": [],
    "product.show": [
        {
            "name": "product",
            "required": true
        }
    ],
    "cart.index": [],
    "cart.add": [],
    "cart.delete": [],
    "cart.update": [],
    "checkout": [],
    "request-order": [],
    "confirmed": [],
    "order.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "order.history": [],
    "order.store": [],
    "order.pay-shipment": [],
    "order.payment-status": [],
    "order.arrived": [
        {
            "name": "id",
            "required": true
        }
    ],
    "order.cancel": [
        {
            "name": "id",
            "required": true
        }
    ],
    "order.review": [],
    "faq": [],
    "admin.dashboard": [],
    "admin.profile.user": [],
    "admin.profile.setting": [],
    "admin.product.index": [],
    "admin.product.create": [],
    "admin.product.store": [],
    "admin.product.edit": [
        {
            "name": "product",
            "required": true
        }
    ],
    "admin.product.update": [
        {
            "name": "product",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.product.delete": [
        {
            "name": "product",
            "required": true
        }
    ],
    "admin.category.index": [],
    "admin.category.store": [],
    "admin.category.update": [
        {
            "name": "category",
            "required": true
        }
    ],
    "admin.category.delete": [
        {
            "name": "category",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.carousel.index": [],
    "admin.carousel.store": [],
    "admin.carousel.update": [
        {
            "name": "carousel",
            "required": true
        }
    ],
    "admin.carousel.delete": [
        {
            "name": "carousel",
            "required": true
        }
    ],
    "admin.customer.index": [],
    "admin.customer.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.customer.review": [],
    "admin.faq.index": [],
    "admin.faq.store": [],
    "admin.faq.update": [
        {
            "name": "faq",
            "required": true
        }
    ],
    "admin.faq.delete": [
        {
            "name": "faq",
            "required": true
        }
    ],
    "admin.analytic.index": [],
    "admin.analytic.export": [],
    "admin.order.index": [],
    "admin.order.confirmation.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.order.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.order.process": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.order.sent": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.order.send": [
        {
            "name": "id",
            "required": true
        }
    ]
}
}
export { };

