@extends('layout.customer')
@section('title', 'home')

@section('content')
    {{-- homapege content container --}}
    <div class="w-full w-max[100%] h-full rounded-3xl bg-[#EFEFEF] shadow-lg text-[#EFEFEF]">
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus esse et modi debitis corrupti repudiandae cum, itaque eveniet molestiae impedit quidem officia quibusdam officiis? Minus fugit dicta deserunt dolor laboriosam?
        Libero minima accusantium asperiores ad ratione tenetur natus mollitia voluptatum, non vero dignissimos labore consectetur quisquam autem sequi perspiciatis amet, explicabo, quos distinctio quo sed dolores. Ad nobis debitis sunt!
        Est, dolorem voluptatibus! A vitae blanditiis iste, beatae mollitia architecto dolorem quae facere quaerat debitis explicabo sapiente nisi nemo dolore quia eligendi esse illum facilis! Aperiam laudantium quidem itaque iure?
        Fuga quae saepe ad repellat explicabo recusandae adipisci quam consequatur nesciunt! Minima, voluptates fugit accusantium unde incidunt deserunt aperiam facere ullam assumenda minus, atque facilis fugiat dignissimos officia cumque vero!
        Aspernatur saepe libero nostrum magnam temporibus asperiores odit nesciunt iste dolor vero atque neque, quaerat id molestias, blanditiis dicta alias hic quibusdam quos veritatis itaque impedit voluptate rerum in. Veniam.
        Cum, praesentium recusandae nisi rerum sequi, dignissimos odit ullam nulla, nam minima cupiditate autem in aliquam unde pariatur dolorum expedita distinctio vel error a ea velit beatae. Minima, veritatis quae.
        Similique voluptatem dolorem aliquid, corrupti recusandae consequatur, dicta et nihil est ipsam distinctio natus debitis perspiciatis non. Distinctio beatae fugit dolor ipsa commodi explicabo, eius enim perferendis tempore totam quas.
        Cum voluptates et magnam necessitatibus excepturi veniam a voluptas corporis veritatis consectetur in fuga maiores, alias tempora ad nisi deleniti exercitationem molestiae? Amet inventore architecto delectus explicabo quis, a doloremque.
        Omnis distinctio, esse nihil vero est ipsam fugit laborum quisquam aliquid quidem corporis et? Ullam dolore labore temporibus fugit explicabo error porro quos, officia tempore sequi nihil, magni quaerat itaque.
        Ex culpa fugiat suscipit, exercitationem quia neque sit! Deserunt fugit mollitia eum minima doloribus magni hic alias rem ad tempore porro illo nostrum aspernatur recusandae reprehenderit corporis laudantium, vel pariatur.
        Laboriosam debitis minus similique? Nobis qui ab repudiandae vero perspiciatis atque enim tenetur, magnam itaque rem voluptate facilis aliquam dolorum. Voluptate in earum perferendis dolor est eaque! Sunt, aperiam laudantium?
        Reiciendis rem repellendus tempora ea corporis in debitis asperiores, quis consequatur numquam, sequi aut suscipit quae nesciunt? Tenetur illo sed asperiores. Porro totam nam debitis dolor doloribus, est libero sequi.
        Cupiditate nulla, cumque, fugiat consectetur quis, fugit doloribus quod odio earum quos nostrum aut sint. Eligendi, sint perspiciatis, esse, placeat architecto blanditiis dignissimos voluptatem vitae qui distinctio at pariatur ut.
        Ab ea eveniet voluptatum minus quibusdam eum, ex saepe? Distinctio nam, temporibus id commodi consectetur quia corrupti mollitia, exercitationem recusandae eveniet hic molestiae sed quos sapiente nesciunt, delectus consequatur natus!
        Eaque officiis illum nostrum quia pariatur expedita sapiente. Sint mollitia itaque illo hic quis voluptatum, sapiente sed, optio aperiam inventore consequuntur consectetur repellat nisi? Aut repellendus omnis suscipit et autem?
        Quaerat magni quidem autem saepe dolores iure doloremque repudiandae omnis deserunt tempora illum, quos voluptates aperiam nobis praesentium perferendis ad molestiae harum cum. Earum, est repellendus hic perferendis nihil nesciunt?
        Quod provident in quia officia aperiam reprehenderit iusto doloribus fuga sapiente iste ab consequatur magni labore facilis atque, repellat cumque accusantium vel totam harum natus sunt voluptatem neque dignissimos. Ea?
        Unde aspernatur laborum voluptates sed ad, officia totam soluta deleniti, eos accusantium inventore libero magnam et perferendis necessitatibus reprehenderit. Non ratione dolorem perspiciatis corrupti odit pariatur voluptas, explicabo nobis asperiores.
        Dolor ullam recusandae totam libero neque doloribus natus ipsa saepe ab sit. Aspernatur deleniti beatae optio ex vitae debitis saepe rerum ducimus labore, aliquam animi dolorem similique? Temporibus, incidunt repellat!
        Aspernatur asperiores fugiat sint nostrum quidem temporibus voluptatem corrupti, eveniet laborum suscipit minus dolorum tenetur quisquam sequi, fuga a excepturi eligendi ipsum facere commodi pariatur consequatur. Consequatur soluta odio nam.
        Vel quia eaque deserunt, harum illo autem dolor magni ipsum perspiciatis blanditiis eveniet impedit aut nostrum animi omnis, voluptate maiores itaque! Quod, illum officia inventore ullam iusto voluptatum totam voluptas.
        Sunt assumenda labore, saepe omnis in dolorum sapiente cum quis veritatis perspiciatis tenetur, impedit, magnam harum porro nesciunt quod. Minima corporis voluptate ex cupiditate quod? Alias, quis aspernatur? Modi, a!
        Esse eveniet facilis eligendi porro accusamus quibusdam, quasi laboriosam deleniti dolor! Exercitationem nostrum ullam sint accusantium ad quam, quisquam officia, velit amet rem quis quod ut deleniti soluta debitis? Alias.
        Recusandae amet ducimus eligendi quaerat quod neque repellendus incidunt laborum aliquid, praesentium eveniet necessitatibus nulla iure officia mollitia ab temporibus at soluta velit reprehenderit doloribus, alias aperiam iste! Iste, obcaecati?
        Facilis blanditiis inventore commodi, dolorum error consequuntur aliquid voluptatibus. Quis iusto voluptatem eligendi voluptas aut sit debitis, quia vitae facere, placeat eos recusandae, fuga ipsa modi ducimus. Architecto, atque sit?
        Deleniti facilis distinctio libero at, repellat facere quo deserunt officiis odio saepe voluptas? Reiciendis deleniti repudiandae, facere odio ab incidunt laboriosam dolorem fuga, totam nesciunt eaque eligendi nemo quibusdam ipsa.
        Corrupti harum in voluptates minus earum, distinctio aliquam molestias soluta sunt alias mollitia libero magnam aperiam dolores velit ipsa voluptatem eum voluptatum perferendis sequi? Voluptatem expedita harum eveniet a voluptatibus!
        Illum libero fugit laboriosam accusantium error totam natus! Nostrum, molestias libero tempora tenetur consectetur vel velit earum! Recusandae, molestias doloribus voluptatibus animi fugiat vitae! Accusantium quidem minima veritatis nesciunt odio.
        Dolore quo eaque dolor adipisci cumque, nihil recusandae iste, tempora id amet facere deserunt itaque eveniet quam! Quas quae fuga commodi ipsam aliquid aut delectus aliquam culpa incidunt, impedit in?
        Voluptate ea similique repudiandae maiores voluptates officia nesciunt nam quos accusamus iure! Possimus tempore nulla delectus, vitae quod dolores aspernatur ratione minus fugit explicabo ullam suscipit, praesentium a dolore labore!
        Excepturi ad natus illo ex facilis eius molestiae ea similique autem, nihil veritatis accusamus voluptate quod eaque placeat amet eligendi iure dolorem! Optio assumenda aut laudantium, voluptatum ullam eum earum!
        In accusantium nihil rerum sequi repudiandae, fuga doloremque quis sunt? Distinctio eius quam nostrum nemo iste excepturi sapiente voluptates nihil, dolorem possimus quaerat ut placeat asperiores minima accusantium vitae doloribus.
        Saepe repellat incidunt totam autem. Nulla eum, odit nisi sequi numquam accusamus delectus dolor obcaecati, debitis incidunt rerum vel necessitatibus! Exercitationem debitis quam reiciendis? Laudantium explicabo aliquid nulla inventore quam.
        Nemo itaque labore dolores, veritatis nulla recusandae architecto obcaecati saepe odio. Dolor natus veniam sapiente numquam voluptates deleniti, cupiditate id ipsum molestias neque blanditiis obcaecati praesentium quidem dignissimos autem vero.
        Ipsum totam aliquid vitae, earum corrupti vel porro facilis recusandae odit nobis eligendi sit id iure doloribus commodi modi itaque illo quis accusamus suscipit, aperiam magni cum quia? Error, repellendus.
        Ut aperiam est rem quo quis pariatur dicta accusantium dolor molestias officia obcaecati ad atque similique voluptatem, quae hic voluptas dolore adipisci enim odio voluptatum. Nulla sequi dolorum fugit rem!
        Voluptates tempore nisi itaque enim tenetur et aliquam aspernatur. Iste expedita ipsum consequatur beatae placeat vel temporibus porro, sit consectetur amet hic esse repellat adipisci officiis odio quos saepe quidem.
        Consequatur, consequuntur ratione. Sunt sint veritatis ullam maxime obcaecati aliquam quo nihil explicabo nam quaerat facilis, asperiores ex beatae, similique quas ea nemo adipisci perferendis culpa cum. Nisi, placeat laboriosam.
        Pariatur, laborum velit repellendus quas facere libero dolor nostrum quibusdam repellat ad nobis aliquam odit cum illum eligendi quam nam fugit quasi dolorem? Facilis beatae possimus odio excepturi nemo velit!
        Repellendus ipsa quia ipsum? Quidem beatae quae nam, itaque ab, nisi ut temporibus excepturi iusto libero fugiat sint porro illum dicta quo sed esse officiis qui laborum, molestias tempora? Magni.
        Dolore delectus maiores esse ea porro molestiae quod officiis in cum modi incidunt eius nostrum aut veniam mollitia quae, nisi minus, illum sunt veritatis repellendus? Doloremque commodi dolores voluptatibus asperiores.
        Perspiciatis asperiores iure impedit sapiente, necessitatibus iusto nulla tempore maxime sed quos quia provident aut et dolorum quo distinctio voluptatem fugiat unde, nisi natus doloremque animi repellat. Rerum, iste ut.
        Est reiciendis saepe eligendi odio cumque illo esse tenetur corporis tempora mollitia et, culpa dicta tempore eum fuga. Ipsum ut veritatis ducimus dolorem, ex natus architecto earum perferendis dignissimos dicta?
        Nobis cupiditate voluptatum facilis maiores minima aut qui pariatur dolores ad illo vel voluptatem, odit officiis ab at velit numquam ea asperiores vitae error! Earum aspernatur exercitationem dolor harum doloribus!
        Possimus sit id ullam eligendi a voluptas. Exercitationem aliquid numquam quisquam, vel, sunt corporis nihil quia fugiat consequatur laboriosam illo tempora earum ipsa sed quidem, eveniet iure aliquam modi quaerat!
        Veniam eos praesentium ipsum obcaecati quae eius sunt vitae adipisci a distinctio provident soluta repellendus amet saepe, nemo dolores. Tempore voluptatem nam esse vero amet repellendus libero illum cupiditate rerum?
        Ut rerum rem, ducimus corporis eveniet ratione itaque illum aperiam distinctio quaerat modi doloremque quasi recusandae quod facilis excepturi nihil labore magni asperiores perspiciatis totam nostrum. Soluta voluptate fugiat cumque?
        Cumque quos error ex quasi quia, animi eius placeat itaque, architecto suscipit sint laborum ipsam soluta modi doloremque officiis ad voluptates natus deserunt velit. Provident dicta aliquid placeat repellendus sint.
        Dolores, illum dignissimos. Ipsum, magnam sunt quo eum iste, labore magni excepturi unde tempore minima voluptates ducimus laudantium qui vero quidem delectus illum minus laborum dolorem quaerat odio perspiciatis possimus.
        Molestiae ea excepturi magnam deserunt consequatur, ipsam voluptatem eveniet voluptas perspiciatis inventore ipsa earum doloremque est expedita, ex, minima modi nulla quo error quod eum voluptate ab? Porro, illo maxime?
    </div>
    {{-- end of homapege content container --}}
@endsection