name: Deploy development server

on:
  workflow_dispatch:
  push:
    branches:
      - development

jobs:
  deploy:
    name: Deploy to development server
    # execute ssh client
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ${{ secrets.WORKDIR }}
            sudo -u www-data git pull
            docker compose up -d --build
